networks:
  default:
    name: "${DOCKER_NAME}-network"
    driver: bridge

services:

  app:

    container_name: "${DOCKER_NAME}-app"

    build:
      context: .
      dockerfile: docker/dockerfile
      args:
        WWWGROUP: "${DOCKER_GID}"
        TIMEZONE: "${DOCKER_TIMEZONE}"

    restart: unless-stopped

    ports:
      - "${APP_HOST_PORT}:81"

    environment:
      WWWUSER: "${DOCKER_UID}"

    volumes:
      - .:/app
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/sites-available/default
      - ./docker/dev/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf

    networks:
      - default