#!/bin/bash

set -e

echo "=================================="
echo "Starting Front Container..."
echo "=================================="

if [ ! -d "/app/node_modules" ]; then
    npm install
fi

npm run build

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf