#!/usr/bin/env bash

if [ "$SUPERVISOR_NODE_USER" != "root" ] && [ "$SUPERVISOR_NODE_USER" != "devuser" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'devuser' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER devuser
fi

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_NODE_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
