# Image of project
FROM ubuntu:20.04

# Arguments
ARG WWWGROUP
ARG TIMEZONE

# Environment variables
ENV DEBIAN_FRONTEND noninteractive
ENV NODE_VERSION=20
ENV USER_GROUP=devgroup
ENV USER_NAME=devuser
ENV SUPERVISOR_NODE_USER=${USER_NAME}
ENV TZ=${TIMEZONE}

# Set timezone
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

# Update package list and make keyrings directory
RUN apt-get update && mkdir -p /etc/apt/keyrings

# Install system dependencies
RUN apt-get install -y \
    gnupg \
    gosu \
    curl \
    wget \
    ca-certificates \
    zip \
    unzip \
    git \
    supervisor \
    dnsutils \
    nano \
    software-properties-common \
    gettext \
    nginx

# Install Node.js
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_VERSION}.x nodistro main" > /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -y nodejs \
    && npm install -g npm \
    && npm install -g @quasar/cli

# Clean
RUN apt-get -y autoremove \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create user and group
RUN groupadd --force -g ${WWWGROUP} ${USER_GROUP}
RUN useradd -ms /bin/bash --no-user-group -g ${WWWGROUP} -u 1337 ${USER_NAME}

# Set working directory
WORKDIR /app

# Start script
COPY start-container /usr/local/bin/start-container
RUN chmod +x /usr/local/bin/start-container

# Init script
ENTRYPOINT ["start-container"]
