name: Build and Deploy Quasar

on:
  push:
    branches:
      - prod

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PUBLIC_PATH: ${{ vars.PUBLIC_PATH }}
      VUE_ROUTER_MODE: ${{ vars.VUE_ROUTER_MODE }}
      APP_VERSION: ${{ vars.APP_VERSION }}
      API_URL: ${{ vars.API_URL }}
      ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Crear .env
        run: |
          echo "PUBLIC_PATH=$PUBLIC_PATH" > .env
          echo "VUE_ROUTER_MODE=$VUE_ROUTER_MODE" >> .env
          echo "APP_VERSION=$APP_VERSION" >> .env
          echo "API_URL=$API_URL" >> .env
          echo "ENCRYPT_KEY=$ENCRYPT_KEY" >> .env

      - name: Build
        run: npm run build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/spa

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4